version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    env_file:
      - docker/server/.env
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    env_file:
      - docker/client/.env
    volumes:
      - client_dist:/usr/share/nginx/html
    ports:
      - "${PORT}:80"

