# =================================================================
# Этап 1: "builder" - Установка зависимостей и сборка клиента
# =================================================================
FROM oven/bun:1 AS builder

WORKDIR /usr/src/app

ARG VITE_APP_SERVER_URL
ARG VITE_APP_SERVER_STATIC_PATH
ARG VITE_APP_API_MODE
ARG VITE_APP_REQUEST_THROTTLE
ARG VITE_MAPTILER_KEY

COPY . .

RUN bun install --ignore-scripts
RUN bun run build

# =================================================================
# Этап 2: "release" - Создание финального образа с Nginx
# =================================================================
FROM nginx:stable-alpine

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
