version: "3.8"

services:
  client:
    image: trip-scheduler-client:${V_CLIENT:-latest}
    container_name: trip-scheduler-client
    ports:
      - "1420:1420"
    restart: always

  server:
    image: trip-scheduler-server:${V_SERVER:-latest}
    container_name: trip-scheduler-server
    ports:
      - "8080:8080"
    networks:
      - trip-net
    env_file:
      - ../apps/server/.env
    volumes:
      - "$HOME/static-data:/usr/src/app/static"
    restart: always

networks:
  trip-net:
    driver: bridge
