version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: trip-scheduler-db
    restart: always
    environment:
      POSTGRES_USER: trip-scheduler
      POSTGRES_PASSWORD: trip-scheduler
      POSTGRES_DB: trip_scheduler_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trip-scheduler -d trip_scheduler_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    container_name: trip-scheduler-server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    restart: always
    env_file:
      - docker/server/.env
    environment:
      DATABASE_URL: "postgresql://trip-scheduler:trip-scheduler@db:5432/trip_scheduler_dev"
      STATIC_PATH: "${STATIC_PATH}"
      FRONTEND_URL: "${FRONTEND_URL}"
      API_URL: "${API_URL}"
      JWT_SECRET: "${JWT_SECRET}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_CALLBACK_URL: "${GOOGLE_CALLBACK_URL}"
      GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
      GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
      GITHUB_CALLBACK_URL: "${GITHUB_CALLBACK_URL}"
    ports:
      - "8080:8080"
    volumes:
      - static_images:/usr/src/app/static/images
    depends_on:
      db:
        condition: service_healthy

  client:
    container_name: trip-scheduler-client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      args:
        VITE_APP_SERVER_URL: ${VITE_APP_SERVER_URL}
        VITE_APP_TRPC_MODE: ${VITE_APP_TRPC_MODE}
        VITE_APP_MOCK_MODE: ${VITE_APP_MOCK_MODE}
        VITE_APP_REQUEST_THROTTLE: ${VITE_APP_REQUEST_THROTTLE}
    restart: always
    env_file:
      - docker/client/.env 
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_images:
