services:
  db:
    image: postgres:15-alpine
    container_name: trip-scheduler-db
    restart: always
    environment:
      POSTGRES_USER: trip-scheduler
      POSTGRES_PASSWORD: trip-scheduler
      POSTGRES_DB: trip_scheduler_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trip-scheduler -d trip_scheduler_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    container_name: trip-scheduler-server
    build:
      context: ..
      dockerfile: deployment/server/Dockerfile
    restart: always
    env_file:
      - .env 
    environment:
      DATABASE_URL: "postgresql://trip-scheduler:trip-scheduler@db:5432/trip_scheduler_dev"
    ports:
      - "8080:8080"
    volumes:
      - static_images:/usr/src/app/static/images
    depends_on:
      db:
        condition: service_healthy

  client:
    container_name: trip-scheduler-client
    build:
      context: ..
      dockerfile: deployment/client/Dockerfile
      args:
        VITE_APP_SERVER_URL: ${VITE_APP_SERVER_URL}
        VITE_APP_TRPC_MODE: ${VITE_APP_TRPC_MODE}
        VITE_APP_MOCK_MODE: ${VITE_APP_MOCK_MODE}
        VITE_APP_REQUEST_THROTTLE: ${VITE_APP_REQUEST_THROTTLE}
    restart: always
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_images:
