server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Эта директива важна для корректной работы роутинга в SPA (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Отключаем логирование для favicon и robots.txt
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Обработка ошибок
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
