import type { Trip } from '~/shared/types/models/trip'

export const MOCK_TRIPS: Trip[] = [
  {
    id: '1',
    title: 'Покорение Алтая',
    imageUrl: '/images/mock.jpg',
    description: 'Активный отдых и треккинг по живописным горам Алтая. Незабываемые виды и приключения.',
    days: 10,
    startDate: '2025-07-15',
    endDate: '2025-07-25',
    cities: ['Горно-Алтайск', 'Акташ'],
    status: 'completed',
    budget: 80000,
    currency: 'RUB',
    participants: ['Алексей', 'Елена'],
    tags: ['горы', 'природа', 'треккинг', 'активный отдых'],
    visibility: 'public',
  },
  {
    id: '2',
    title: 'Неоновый Гонконг',
    imageUrl: '/images/mock-2.png',
    description: 'Погружение в атмосферу азиатского мегаполиса: от небоскребов до уличной еды.',
    days: 7,
    startDate: '2025-09-10',
    endDate: '2025-09-17',
    cities: ['Гонконг'],
    status: 'planned',
    budget: 1500,
    currency: 'USD',
    participants: ['Максим'],
    tags: ['город', 'культура', 'еда', 'Азия'],
    visibility: 'private',
  },
  {
    id: '3',
    title: 'Путешествие в Японию',
    imageUrl: '/images/mock.jpg',
    description: 'Весеннее путешествие в страну восходящего солнца во время цветения сакуры.',
    days: 14,
    startDate: '2026-03-25',
    endDate: '2026-04-08',
    cities: ['Токио', 'Киото', 'Осака'],
    status: 'draft',
    budget: 3500,
    currency: 'USD',
    participants: ['Анна', 'Дмитрий'],
    tags: ['Япония', 'сакура', 'весна', 'культура'],
    visibility: 'private',
  },
]
