use crate::ITrip;

pub fn get_mock_plans() -> Vec<ITrip> {
    vec![
        ITrip {
            id: "1".to_string(),
            title: "Покорение Алтая".to_string(),
            image_url: Some("/images/mock.jpg".to_string()),
            description: Some("Активный отдых и треккинг по живописным горам Алтая. Незабываемые виды и приключения.".to_string()),
            days: Some(10),
            start_date: Some("2025-07-15".to_string()),
            end_date: Some("2025-07-25".to_string()),
            cities: Some(vec!["Горно-Алтайск".to_string(), "Акташ".to_string()]),
            status: Some("completed".to_string()),
            budget: Some(80000.0),
            currency: Some("RUB".to_string()),
            participants: Some(vec!["Алексей".to_string(), "Елена".to_string()]),
            tags: Some(vec!["горы".to_string(), "природа".to_string(), "треккинг".to_string(), "активный отдых".to_string()]),
            visibility: Some("public".to_string()),
        },
        ITrip {
            id: "2".to_string(),
            title: "Неоновый Гонконг".to_string(),
            image_url: Some("/images/mock-2.png".to_string()),
            description: Some("Погружение в атмосферу азиатского мегаполиса: от небоскребов до уличной еды.".to_string()),
            days: Some(7),
            start_date: Some("2025-09-10".to_string()),
            end_date: Some("2025-09-17".to_string()),
            cities: Some(vec!["Гонконг".to_string()]),
            status: Some("planned".to_string()),
            budget: Some(1500.0),
            currency: Some("USD".to_string()),
            participants: Some(vec!["Максим".to_string()]),
            tags: Some(vec!["город".to_string(), "культура".to_string(), "еда".to_string(), "Азия".to_string()]),
            visibility: Some("private".to_string()),
        },
        ITrip {
            id: "3".to_string(),
            title: "Путешествие в Японию".to_string(),
            image_url: Some("/images/mock.jpg".to_string()),
            description: Some("Весеннее путешествие в страну восходящего солнца во время цветения сакуры.".to_string()),
            days: Some(14),
            start_date: Some("2026-03-25".to_string()),
            end_date: Some("2026-04-08".to_string()),
            cities: Some(vec!["Токио".to_string(), "Киото".to_string(), "Осака".to_string()]),
            status: Some("draft".to_string()),
            budget: Some(3500.0),
            currency: Some("USD".to_string()),
            participants: Some(vec!["Анна".to_string(), "Дмитрий".to_string()]),
            tags: Some(vec!["Япония".to_string(), "сакура".to_string(), "весна".to_string(), "культура".to_string()]),
            visibility: Some("private".to_string()),
        },
    ]
}
